apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "eternium-agent.labels" . | nindent 4 }}
  name: {{ include "eternium-agent.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "eternium-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "eternium-agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      {{- if .Values.image.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.image.imagePullSecrets }}
      {{- end}}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # Load configuration from our ConfigMap and Secret templates
          envFrom:
            - secretRef:
                name: {{ .Values.secrets.name }}
            - configMapRef:
                name: {{ .Values.config.name }}
          # Liveness and readiness probes are good practice for production
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
