{{- if .Values.ingress.enabled}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    {{- include "eternium-agent.labels" . | nindent 4 }}
  name: {{ include "eternium-agent.fullname" . }}-ingress
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "eternium-agent.fullname" . }}-svc
              port:
                number: {{ .Values.service.port }}
  {{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
  - hosts:
      {{- range .hosts }}
      - {{ . }}
      {{- end }}
    secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
{{- end }}
