apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "eternium-agent.labels" . | nindent 4 }}
  name: {{ include "eternium-agent.fullname" . }}-svc
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "eternium-agent.selectorLabels" . | nindent 4 }}
